name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node and install dependencies
        uses: ./.github/actions/setup

      - name: Publish extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run publish -- -p "$VSCE_PAT"
